### ISSUE TITLE
please don't calculate versions based on build time

### ISSUE THREAD

**Issue by IzzySoft** [Kwasow/Musekit#9]
You currently seem to [calculate your versions](https://github.com/Kwasow/Musekit/blob/main/app/build.gradle.kts#L7) based on build time. This makes [Reproducible Builds](https://reproducible-builds.org/) (also see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)) rather difficult, as it requires manual adjustments of the build recipes for each new release. Could you switch to something that does not vary based on when the app is being built? Thanks in advance!

**Comment by Kwasow** [comment]
Sure, I already updated some other active projects I work one away from timed versioning, mostly because the number will get too big at some point and I don't see any work being done to extend the size of version numbers. I'll update the code soon, thanks for reminding me.

**Comment by IzzySoft** [comment]
Cool, thanks! If you could give me a small ping here shortly before the first release with that change comes out, that would be great – then I can update the recipe of the verification builder here once the build fails :stuck_out_tongue_winking_eye: Though I should get a ping once you close this issue :wink:

Btw, I see you use some shields on the readme. Want to add one for the presence of your app at IzzyOnDroid? You can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and/or a shield, whichever you like.

[<img src="https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/com.kwasow.musekit">](https://apt.izzysoft.de/packages/com.kwasow.musekit)

**Comment by Kwasow** [comment]
The new release is live [here](https://github.com/Kwasow/Musekit/releases/tag/v1.4.1) and will also soon be available on the Play Store. Once again, thanks for reminding me to update this.

**Comment by IzzySoft** [comment]
Confirming the versioning issue fixed: RB succeeded without any adjustments, thanks! But something went wrong, still: `versionCode` is lower than that of the previous release:

* v1.4.1: 1721768329
* v1.4.0: 1721768579

![image](https://github.com/user-attachments/assets/b21701d9-f7bf-47cb-9f4e-b989c571364c)

So the "update" won't reach anyone – and those trying to update to it manually won't succeed as Android does not allow for downgrades. Which means you might need a v1.4.2 soon adjusting accordingly (please do **not** replace the existing 1.4.1 or its APK now that it's out).

> will also soon be available on the Play Store

Will be at IzzyOnDroid (see initial post) even earlier: around 6 pm UTC, to be more precise. With the green shield, of course :wink: 

Scanner reported something you might wish to care for, though:

    ! repo/com.kwasow.musekit_1721768329.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)

Easily solved with a minor adjustment to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

**Comment by Kwasow** [comment]
> versionCode is lower than that of the previous release:
> v1.4.1: 1721768329
> v1.4.0: 1721768579

Right, my bad. I took the previous version code from the Play Store, but forgot that I usually build the Play Store bundle first and then the GitHub APK. A new release `1.4.2` is available now, with the correct version code.

**Comment by IzzySoft** [comment]
Thanks, that fully fits again (`versionCode`**and** RB) :partying_face:
